# Example without new configmaps and secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run-type: stable
    app: nginx-new
  name: nginx-new
spec:
  replicas: 1
  selector:
    matchLabels:
      run-type: stable
      app: nginx-new
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        run-type: stable
        app: nginx-new
    spec:
      containers:
      - image: nginx:1.26-alpine
        imagePullPolicy: IfNotPresent
        name: nginx-new
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-new
spec:
  selector:
    app: nginx-new
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-new
spec:
  host: nginx-new
  subsets:
  - name: stable
    labels:
      run-type: stable
  - name: canary
    labels:
      run-type: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-new-vs
spec:
  hosts:
  - nginx-new
  http:
  - route:
    - destination:
        host: nginx-new
        subset: stable
      weight: 100
    - destination:
        host: nginx-new
        subset: canary
      weight: 0