---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mox-app-br-v1alpha1-canarydeployment
  failurePolicy: Fail
  name: mcanarydeployment-v1alpha1.kb.io
  rules:
  - apiGroups:
    - mox.app.br.mox.app.br
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - canarydeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mox-app-br-v1alpha1-canarydeployment
  failurePolicy: Fail
  name: vcanarydeployment-v1alpha1.kb.io
  rules:
  - apiGroups:
    - mox.app.br.mox.app.br
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - canarydeployments
  sideEffects: None
