# This rule is not used by the project go-examples itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the mox.app.br.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: canary-deployments
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-editor-role
rules:
- apiGroups:
  - mox.app.br
  resources:
  - canarydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mox.app.br
  resources:
  - canarydeployments/status
  verbs:
  - get
# - apiGroups:
#   - networking.istio.io/v1
#   resources:
#   - virtualservices
#   verbs:
#   - create
#   - delete
#   - get
#   - list
#   - patch
#   - update
#   - watch
# - apiGroups:
#   - networking.istio.io/v1
#   resources:
#   - virtualservices/status
#   verbs:
#   - get
