apiVersion: mox.app.br/v1alpha1
kind: CanaryDeployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-1
spec:
  appName: nginx
  stable: "1.26-alpine"
  canary: "1.27-alpine"
  steps:
  - setWeight: 10
    pause: {seconds: 5}
  # - setWeight: 20
  #   pause: {seconds: 11}
  # - setWeight: 50
  #   pause: {seconds: 12}
  # - setWeight: 90
  #   pause: {seconds: 14}
  - setWeight: 100
---
apiVersion: mox.app.br/v1alpha1
kind: CanaryDeployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-2
spec:
  appName: nginx-new
  stable: "1.26-alpine"
  canary: "1.27-alpine"
  steps:
  # - setWeight: 8
  #   pause: {seconds: 20}
  # - setWeight: 16
  #   pause: {seconds: 10}
  # - setWeight: 45
  #   pause: {seconds: 10}
  # - setWeight: 78
  #   pause: {seconds: 10}
  - setWeight: 98
    pause: {seconds: 5}
  - setWeight: 100