apiVersion: mox.app.br/v1alpha1
kind: CanaryDeployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-1
spec:
  appName: nginx
  stable: "1.26-alpine"
  canary: "1.27-alpine"
  istioVirtualServiceName: nginx-vs
  configMapNames:
  - nginx-new1-env
  - nginx-new2-env
  secretNames:
  - nginx-secret
  steps:
    - weight: 10
      pause:
        seconds: 60
    - weight: 25
      pause:
        minutes: 2
    - weight: 50
      pause:
        minutes: 5
    - weight: 100
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  PASS: MTIzNA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-new1-env
data:
  APP_NAME: "nginx-canary"
  LEVEL: "debug"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-new2-env
data:
  APP_NAME: "nginx-canary"
  LEVEL: "debug"