apiVersion: mox.app.br/v1alpha1
kind: CanaryDeployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-1
spec:
  appName: nginx
  stable: "1.26-alpine"
  canary: "1.27-alpine"
  steps:
  - setWeight: 10
    pause: {seconds: 60}
  - setWeight: 20
    pause: {seconds: 60}
  - setWeight: 45
    pause: {seconds: 60}
  - setWeight: 70
    pause: {minutes: 2}
  - setWeight: 100
---
apiVersion: mox.app.br/v1alpha1
kind: CanaryDeployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: canarydeployment-2
spec:
  appName: nginx-new
  stable: "1.26-alpine"
  canary: "1.27-alpine"
  steps:
  - setWeight: 10
    pause: {seconds: 120}
  - setWeight: 20
    pause: {seconds: 90}
  - setWeight: 55
    pause: {seconds: 240}
  - setWeight: 82
    pause: {seconds: 90}
  - setWeight: 89
    pause: {minutes: 5}
  - setWeight: 100